// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gururuby/shortener/internal/domain/usecase/stats (interfaces: StatsStorage)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock.go -package=mocks . StatsStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/gururuby/shortener/internal/domain/entity/stats"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsStorage is a mock of StatsStorage interface.
type MockStatsStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStatsStorageMockRecorder
	isgomock struct{}
}

// MockStatsStorageMockRecorder is the mock recorder for MockStatsStorage.
type MockStatsStorageMockRecorder struct {
	mock *MockStatsStorage
}

// NewMockStatsStorage creates a new mock instance.
func NewMockStatsStorage(ctrl *gomock.Controller) *MockStatsStorage {
	mock := &MockStatsStorage{ctrl: ctrl}
	mock.recorder = &MockStatsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsStorage) EXPECT() *MockStatsStorageMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsStorage) GetStats(ctx context.Context) (*entity.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(*entity.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsStorageMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsStorage)(nil).GetStats), ctx)
}
