// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/http/shorturl.go
//
// Generated by this command:
//
//      mockgen -source=internal/handler/http/shorturl.go
//

// Package mock_handler is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockshortURLUseCase is a mock of shortURLUseCase interface.
type MockshortURLUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockshortURLUseCaseMockRecorder
	isgomock struct{}
}

// MockshortURLUseCaseMockRecorder is the mock recorder for MockshortURLUseCase.
type MockshortURLUseCaseMockRecorder struct {
	mock *MockshortURLUseCase
}

// NewMockshortURLUseCase creates a new mock instance.
func NewMockshortURLUseCase(ctrl *gomock.Controller) *MockshortURLUseCase {
	mock := &MockshortURLUseCase{ctrl: ctrl}
	mock.recorder = &MockshortURLUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockshortURLUseCase) EXPECT() *MockshortURLUseCaseMockRecorder {
	return m.recorder
}

// CreateShortURL mocks base method.
func (m *MockshortURLUseCase) CreateShortURL(sourceURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", sourceURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockshortURLUseCaseMockRecorder) CreateShortURL(sourceURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockshortURLUseCase)(nil).CreateShortURL), sourceURL)
}

// FindShortURL mocks base method.
func (m *MockshortURLUseCase) FindShortURL(alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindShortURL", alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindShortURL indicates an expected call of FindShortURL.
func (mr *MockshortURLUseCaseMockRecorder) FindShortURL(alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindShortURL", reflect.TypeOf((*MockshortURLUseCase)(nil).FindShortURL), alias)
}
