// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: internal/grpc/app/app.proto

package app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBRequest) Reset() {
	*x = PingDBRequest{}
	mi := &file_internal_grpc_app_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBRequest) ProtoMessage() {}

func (x *PingDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_app_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBRequest.ProtoReflect.Descriptor instead.
func (*PingDBRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_app_app_proto_rawDescGZIP(), []int{0}
}

type PingDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingDBResponse) Reset() {
	*x = PingDBResponse{}
	mi := &file_internal_grpc_app_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDBResponse) ProtoMessage() {}

func (x *PingDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_app_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDBResponse.ProtoReflect.Descriptor instead.
func (*PingDBResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_app_app_proto_rawDescGZIP(), []int{1}
}

func (x *PingDBResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PingDBResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_grpc_app_app_proto protoreflect.FileDescriptor

const file_internal_grpc_app_app_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/grpc/app/app.proto\x12\x03app\"\x0f\n" +
	"\rPingDBRequest\"@\n" +
	"\x0ePingDBResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2?\n" +
	"\n" +
	"AppService\x121\n" +
	"\x06PingDB\x12\x12.app.PingDBRequest\x1a\x13.app.PingDBResponseB1Z/github.com/gururuby/shortener/internal/grpc/appb\x06proto3"

var (
	file_internal_grpc_app_app_proto_rawDescOnce sync.Once
	file_internal_grpc_app_app_proto_rawDescData []byte
)

func file_internal_grpc_app_app_proto_rawDescGZIP() []byte {
	file_internal_grpc_app_app_proto_rawDescOnce.Do(func() {
		file_internal_grpc_app_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_app_app_proto_rawDesc), len(file_internal_grpc_app_app_proto_rawDesc)))
	})
	return file_internal_grpc_app_app_proto_rawDescData
}

var file_internal_grpc_app_app_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_app_app_proto_goTypes = []any{
	(*PingDBRequest)(nil),  // 0: app.PingDBRequest
	(*PingDBResponse)(nil), // 1: app.PingDBResponse
}
var file_internal_grpc_app_app_proto_depIdxs = []int32{
	0, // 0: app.AppService.PingDB:input_type -> app.PingDBRequest
	1, // 1: app.AppService.PingDB:output_type -> app.PingDBResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_app_app_proto_init() }
func file_internal_grpc_app_app_proto_init() {
	if File_internal_grpc_app_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_app_app_proto_rawDesc), len(file_internal_grpc_app_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_app_app_proto_goTypes,
		DependencyIndexes: file_internal_grpc_app_app_proto_depIdxs,
		MessageInfos:      file_internal_grpc_app_app_proto_msgTypes,
	}.Build()
	File_internal_grpc_app_app_proto = out.File
	file_internal_grpc_app_app_proto_goTypes = nil
	file_internal_grpc_app_app_proto_depIdxs = nil
}
