// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gururuby/shortener/internal/handler/http/shorturl (interfaces: UserUseCase,ShortURLUseCase)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock.go -package=mocks . UserUseCase,ShortURLUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/gururuby/shortener/internal/domain/entity/shorturl"
	entity0 "github.com/gururuby/shortener/internal/domain/entity/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserUseCase is a mock of UserUseCase interface.
type MockUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUseCaseMockRecorder
	isgomock struct{}
}

// MockUserUseCaseMockRecorder is the mock recorder for MockUserUseCase.
type MockUserUseCaseMockRecorder struct {
	mock *MockUserUseCase
}

// NewMockUserUseCase creates a new mock instance.
func NewMockUserUseCase(ctrl *gomock.Controller) *MockUserUseCase {
	mock := &MockUserUseCase{ctrl: ctrl}
	mock.recorder = &MockUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUseCase) EXPECT() *MockUserUseCaseMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockUserUseCase) Authenticate(ctx context.Context, token string) (*entity0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, token)
	ret0, _ := ret[0].(*entity0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockUserUseCaseMockRecorder) Authenticate(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockUserUseCase)(nil).Authenticate), ctx, token)
}

// Register mocks base method.
func (m *MockUserUseCase) Register(ctx context.Context) (*entity0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx)
	ret0, _ := ret[0].(*entity0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserUseCaseMockRecorder) Register(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserUseCase)(nil).Register), ctx)
}

// MockShortURLUseCase is a mock of ShortURLUseCase interface.
type MockShortURLUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLUseCaseMockRecorder
	isgomock struct{}
}

// MockShortURLUseCaseMockRecorder is the mock recorder for MockShortURLUseCase.
type MockShortURLUseCaseMockRecorder struct {
	mock *MockShortURLUseCase
}

// NewMockShortURLUseCase creates a new mock instance.
func NewMockShortURLUseCase(ctrl *gomock.Controller) *MockShortURLUseCase {
	mock := &MockShortURLUseCase{ctrl: ctrl}
	mock.recorder = &MockShortURLUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLUseCase) EXPECT() *MockShortURLUseCaseMockRecorder {
	return m.recorder
}

// BatchShortURLs mocks base method.
func (m *MockShortURLUseCase) BatchShortURLs(ctx context.Context, urls []entity.BatchShortURLInput) []entity.BatchShortURLOutput {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchShortURLs", ctx, urls)
	ret0, _ := ret[0].([]entity.BatchShortURLOutput)
	return ret0
}

// BatchShortURLs indicates an expected call of BatchShortURLs.
func (mr *MockShortURLUseCaseMockRecorder) BatchShortURLs(ctx, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchShortURLs", reflect.TypeOf((*MockShortURLUseCase)(nil).BatchShortURLs), ctx, urls)
}

// CreateShortURL mocks base method.
func (m *MockShortURLUseCase) CreateShortURL(ctx context.Context, user *entity0.User, sourceURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", ctx, user, sourceURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockShortURLUseCaseMockRecorder) CreateShortURL(ctx, user, sourceURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockShortURLUseCase)(nil).CreateShortURL), ctx, user, sourceURL)
}

// FindShortURL mocks base method.
func (m *MockShortURLUseCase) FindShortURL(ctx context.Context, alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindShortURL", ctx, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindShortURL indicates an expected call of FindShortURL.
func (mr *MockShortURLUseCaseMockRecorder) FindShortURL(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindShortURL", reflect.TypeOf((*MockShortURLUseCase)(nil).FindShortURL), ctx, alias)
}
