// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: internal/grpc/shorturl/shorturl.proto

package shorturl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLRequest) Reset() {
	*x = CreateShortURLRequest{}
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLRequest) ProtoMessage() {}

func (x *CreateShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLRequest.ProtoReflect.Descriptor instead.
func (*CreateShortURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_shorturl_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortURLRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *CreateShortURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Conflict      bool                   `protobuf:"varint,3,opt,name=conflict,proto3" json:"conflict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortURLResponse) Reset() {
	*x = CreateShortURLResponse{}
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortURLResponse) ProtoMessage() {}

func (x *CreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*CreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_shorturl_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortURLResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CreateShortURLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateShortURLResponse) GetConflict() bool {
	if x != nil {
		return x.Conflict
	}
	return false
}

type BatchShortURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Urls          []*BatchURLInput       `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortURLsRequest) Reset() {
	*x = BatchShortURLsRequest{}
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortURLsRequest) ProtoMessage() {}

func (x *BatchShortURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortURLsRequest.ProtoReflect.Descriptor instead.
func (*BatchShortURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_shorturl_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *BatchShortURLsRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *BatchShortURLsRequest) GetUrls() []*BatchURLInput {
	if x != nil {
		return x.Urls
	}
	return nil
}

type BatchURLInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLInput) Reset() {
	*x = BatchURLInput{}
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLInput) ProtoMessage() {}

func (x *BatchURLInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLInput.ProtoReflect.Descriptor instead.
func (*BatchURLInput) Descriptor() ([]byte, []int) {
	return file_internal_grpc_shorturl_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *BatchURLInput) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchURLInput) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchShortURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*BatchURLOutput      `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchShortURLsResponse) Reset() {
	*x = BatchShortURLsResponse{}
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchShortURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchShortURLsResponse) ProtoMessage() {}

func (x *BatchShortURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchShortURLsResponse.ProtoReflect.Descriptor instead.
func (*BatchShortURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_shorturl_shorturl_proto_rawDescGZIP(), []int{4}
}

func (x *BatchShortURLsResponse) GetUrls() []*BatchURLOutput {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *BatchShortURLsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchURLOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchURLOutput) Reset() {
	*x = BatchURLOutput{}
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchURLOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchURLOutput) ProtoMessage() {}

func (x *BatchURLOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchURLOutput.ProtoReflect.Descriptor instead.
func (*BatchURLOutput) Descriptor() ([]byte, []int) {
	return file_internal_grpc_shorturl_shorturl_proto_rawDescGZIP(), []int{5}
}

func (x *BatchURLOutput) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchURLOutput) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type FindShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindShortURLRequest) Reset() {
	*x = FindShortURLRequest{}
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindShortURLRequest) ProtoMessage() {}

func (x *FindShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindShortURLRequest.ProtoReflect.Descriptor instead.
func (*FindShortURLRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_shorturl_shorturl_proto_rawDescGZIP(), []int{6}
}

func (x *FindShortURLRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type FindShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Gone          bool                   `protobuf:"varint,3,opt,name=gone,proto3" json:"gone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindShortURLResponse) Reset() {
	*x = FindShortURLResponse{}
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindShortURLResponse) ProtoMessage() {}

func (x *FindShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_shorturl_shorturl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindShortURLResponse.ProtoReflect.Descriptor instead.
func (*FindShortURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_shorturl_shorturl_proto_rawDescGZIP(), []int{7}
}

func (x *FindShortURLResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *FindShortURLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FindShortURLResponse) GetGone() bool {
	if x != nil {
		return x.Gone
	}
	return false
}

var File_internal_grpc_shorturl_shorturl_proto protoreflect.FileDescriptor

const file_internal_grpc_shorturl_shorturl_proto_rawDesc = "" +
	"\n" +
	"%internal/grpc/shorturl/shorturl.proto\x12\bshorturl\"H\n" +
	"\x15CreateShortURLRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"b\n" +
	"\x16CreateShortURLResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1a\n" +
	"\bconflict\x18\x03 \x01(\bR\bconflict\"c\n" +
	"\x15BatchShortURLsRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12+\n" +
	"\x04urls\x18\x02 \x03(\v2\x17.shorturl.BatchURLInputR\x04urls\"Y\n" +
	"\rBatchURLInput\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"\\\n" +
	"\x16BatchShortURLsResponse\x12,\n" +
	"\x04urls\x18\x01 \x03(\v2\x18.shorturl.BatchURLOutputR\x04urls\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"T\n" +
	"\x0eBatchURLOutput\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"+\n" +
	"\x13FindShortURLRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\\\n" +
	"\x14FindShortURLResponse\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04gone\x18\x03 \x01(\bR\x04gone2\x8a\x02\n" +
	"\x0fShortURLService\x12S\n" +
	"\x0eCreateShortURL\x12\x1f.shorturl.CreateShortURLRequest\x1a .shorturl.CreateShortURLResponse\x12S\n" +
	"\x0eBatchShortURLs\x12\x1f.shorturl.BatchShortURLsRequest\x1a .shorturl.BatchShortURLsResponse\x12M\n" +
	"\fFindShortURL\x12\x1d.shorturl.FindShortURLRequest\x1a\x1e.shorturl.FindShortURLResponseB6Z4github.com/gururuby/shortener/internal/grpc/shorturlb\x06proto3"

var (
	file_internal_grpc_shorturl_shorturl_proto_rawDescOnce sync.Once
	file_internal_grpc_shorturl_shorturl_proto_rawDescData []byte
)

func file_internal_grpc_shorturl_shorturl_proto_rawDescGZIP() []byte {
	file_internal_grpc_shorturl_shorturl_proto_rawDescOnce.Do(func() {
		file_internal_grpc_shorturl_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_shorturl_shorturl_proto_rawDesc), len(file_internal_grpc_shorturl_shorturl_proto_rawDesc)))
	})
	return file_internal_grpc_shorturl_shorturl_proto_rawDescData
}

var file_internal_grpc_shorturl_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_grpc_shorturl_shorturl_proto_goTypes = []any{
	(*CreateShortURLRequest)(nil),  // 0: shorturl.CreateShortURLRequest
	(*CreateShortURLResponse)(nil), // 1: shorturl.CreateShortURLResponse
	(*BatchShortURLsRequest)(nil),  // 2: shorturl.BatchShortURLsRequest
	(*BatchURLInput)(nil),          // 3: shorturl.BatchURLInput
	(*BatchShortURLsResponse)(nil), // 4: shorturl.BatchShortURLsResponse
	(*BatchURLOutput)(nil),         // 5: shorturl.BatchURLOutput
	(*FindShortURLRequest)(nil),    // 6: shorturl.FindShortURLRequest
	(*FindShortURLResponse)(nil),   // 7: shorturl.FindShortURLResponse
}
var file_internal_grpc_shorturl_shorturl_proto_depIdxs = []int32{
	3, // 0: shorturl.BatchShortURLsRequest.urls:type_name -> shorturl.BatchURLInput
	5, // 1: shorturl.BatchShortURLsResponse.urls:type_name -> shorturl.BatchURLOutput
	0, // 2: shorturl.ShortURLService.CreateShortURL:input_type -> shorturl.CreateShortURLRequest
	2, // 3: shorturl.ShortURLService.BatchShortURLs:input_type -> shorturl.BatchShortURLsRequest
	6, // 4: shorturl.ShortURLService.FindShortURL:input_type -> shorturl.FindShortURLRequest
	1, // 5: shorturl.ShortURLService.CreateShortURL:output_type -> shorturl.CreateShortURLResponse
	4, // 6: shorturl.ShortURLService.BatchShortURLs:output_type -> shorturl.BatchShortURLsResponse
	7, // 7: shorturl.ShortURLService.FindShortURL:output_type -> shorturl.FindShortURLResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_shorturl_shorturl_proto_init() }
func file_internal_grpc_shorturl_shorturl_proto_init() {
	if File_internal_grpc_shorturl_shorturl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_shorturl_shorturl_proto_rawDesc), len(file_internal_grpc_shorturl_shorturl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_shorturl_shorturl_proto_goTypes,
		DependencyIndexes: file_internal_grpc_shorturl_shorturl_proto_depIdxs,
		MessageInfos:      file_internal_grpc_shorturl_shorturl_proto_msgTypes,
	}.Build()
	File_internal_grpc_shorturl_shorturl_proto = out.File
	file_internal_grpc_shorturl_shorturl_proto_goTypes = nil
	file_internal_grpc_shorturl_shorturl_proto_depIdxs = nil
}
