// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gururuby/shortener/internal/domain/storage/stats (interfaces: StatsDB)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock.go -package=mocks . StatsDB
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/gururuby/shortener/internal/domain/entity/stats"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsDB is a mock of StatsDB interface.
type MockStatsDB struct {
	ctrl     *gomock.Controller
	recorder *MockStatsDBMockRecorder
	isgomock struct{}
}

// MockStatsDBMockRecorder is the mock recorder for MockStatsDB.
type MockStatsDBMockRecorder struct {
	mock *MockStatsDB
}

// NewMockStatsDB creates a new mock instance.
func NewMockStatsDB(ctrl *gomock.Controller) *MockStatsDB {
	mock := &MockStatsDB{ctrl: ctrl}
	mock.recorder = &MockStatsDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsDB) EXPECT() *MockStatsDBMockRecorder {
	return m.recorder
}

// GetResourcesCounts mocks base method.
func (m *MockStatsDB) GetResourcesCounts(ctx context.Context) (*entity.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourcesCounts", ctx)
	ret0, _ := ret[0].(*entity.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourcesCounts indicates an expected call of GetResourcesCounts.
func (mr *MockStatsDBMockRecorder) GetResourcesCounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourcesCounts", reflect.TypeOf((*MockStatsDB)(nil).GetResourcesCounts), ctx)
}
