// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: internal/grpc/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLsRequest) Reset() {
	*x = GetURLsRequest{}
	mi := &file_internal_grpc_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsRequest) ProtoMessage() {}

func (x *GetURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsRequest.ProtoReflect.Descriptor instead.
func (*GetURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetURLsRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type GetURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURL             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLsResponse) Reset() {
	*x = GetURLsResponse{}
	mi := &file_internal_grpc_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLsResponse) ProtoMessage() {}

func (x *GetURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLsResponse.ProtoReflect.Descriptor instead.
func (*GetURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetURLsResponse) GetUrls() []*UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *GetURLsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURL) Reset() {
	*x = UserURL{}
	mi := &file_internal_grpc_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURL) ProtoMessage() {}

func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURL.ProtoReflect.Descriptor instead.
func (*UserURL) Descriptor() ([]byte, []int) {
	return file_internal_grpc_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type DeleteURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Aliases       []string               `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLsRequest) Reset() {
	*x = DeleteURLsRequest{}
	mi := &file_internal_grpc_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsRequest) ProtoMessage() {}

func (x *DeleteURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteURLsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteURLsRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *DeleteURLsRequest) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

type DeleteURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLsResponse) Reset() {
	*x = DeleteURLsResponse{}
	mi := &file_internal_grpc_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLsResponse) ProtoMessage() {}

func (x *DeleteURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteURLsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteURLsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteURLsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_grpc_user_user_proto protoreflect.FileDescriptor

const file_internal_grpc_user_user_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/grpc/user/user.proto\x12\x04user\"/\n" +
	"\x0eGetURLsRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"J\n" +
	"\x0fGetURLsResponse\x12!\n" +
	"\x04urls\x18\x01 \x03(\v2\r.user.UserURLR\x04urls\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"I\n" +
	"\aUserURL\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"L\n" +
	"\x11DeleteURLsRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\"D\n" +
	"\x12DeleteURLsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x86\x01\n" +
	"\vUserService\x126\n" +
	"\aGetURLs\x12\x14.user.GetURLsRequest\x1a\x15.user.GetURLsResponse\x12?\n" +
	"\n" +
	"DeleteURLs\x12\x17.user.DeleteURLsRequest\x1a\x18.user.DeleteURLsResponseB2Z0github.com/gururuby/shortener/internal/grpc/userb\x06proto3"

var (
	file_internal_grpc_user_user_proto_rawDescOnce sync.Once
	file_internal_grpc_user_user_proto_rawDescData []byte
)

func file_internal_grpc_user_user_proto_rawDescGZIP() []byte {
	file_internal_grpc_user_user_proto_rawDescOnce.Do(func() {
		file_internal_grpc_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_user_user_proto_rawDesc), len(file_internal_grpc_user_user_proto_rawDesc)))
	})
	return file_internal_grpc_user_user_proto_rawDescData
}

var file_internal_grpc_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_grpc_user_user_proto_goTypes = []any{
	(*GetURLsRequest)(nil),     // 0: user.GetURLsRequest
	(*GetURLsResponse)(nil),    // 1: user.GetURLsResponse
	(*UserURL)(nil),            // 2: user.UserURL
	(*DeleteURLsRequest)(nil),  // 3: user.DeleteURLsRequest
	(*DeleteURLsResponse)(nil), // 4: user.DeleteURLsResponse
}
var file_internal_grpc_user_user_proto_depIdxs = []int32{
	2, // 0: user.GetURLsResponse.urls:type_name -> user.UserURL
	0, // 1: user.UserService.GetURLs:input_type -> user.GetURLsRequest
	3, // 2: user.UserService.DeleteURLs:input_type -> user.DeleteURLsRequest
	1, // 3: user.UserService.GetURLs:output_type -> user.GetURLsResponse
	4, // 4: user.UserService.DeleteURLs:output_type -> user.DeleteURLsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_grpc_user_user_proto_init() }
func file_internal_grpc_user_user_proto_init() {
	if File_internal_grpc_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_user_user_proto_rawDesc), len(file_internal_grpc_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_user_user_proto_goTypes,
		DependencyIndexes: file_internal_grpc_user_user_proto_depIdxs,
		MessageInfos:      file_internal_grpc_user_user_proto_msgTypes,
	}.Build()
	File_internal_grpc_user_user_proto = out.File
	file_internal_grpc_user_user_proto_goTypes = nil
	file_internal_grpc_user_user_proto_depIdxs = nil
}
