// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gururuby/shortener/internal/domain/storage/user (interfaces: UserDB)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock.go -package=mocks . UserDB
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/gururuby/shortener/internal/domain/entity/shorturl"
	entity0 "github.com/gururuby/shortener/internal/domain/entity/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserDB is a mock of UserDB interface.
type MockUserDB struct {
	ctrl     *gomock.Controller
	recorder *MockUserDBMockRecorder
	isgomock struct{}
}

// MockUserDBMockRecorder is the mock recorder for MockUserDB.
type MockUserDBMockRecorder struct {
	mock *MockUserDB
}

// NewMockUserDB creates a new mock instance.
func NewMockUserDB(ctrl *gomock.Controller) *MockUserDB {
	mock := &MockUserDB{ctrl: ctrl}
	mock.recorder = &MockUserDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDB) EXPECT() *MockUserDBMockRecorder {
	return m.recorder
}

// FindUser mocks base method.
func (m *MockUserDB) FindUser(ctx context.Context, id int) (*entity0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUser", ctx, id)
	ret0, _ := ret[0].(*entity0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUser indicates an expected call of FindUser.
func (mr *MockUserDBMockRecorder) FindUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUser", reflect.TypeOf((*MockUserDB)(nil).FindUser), ctx, id)
}

// FindUserURLs mocks base method.
func (m *MockUserDB) FindUserURLs(ctx context.Context, id int) ([]*entity.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserURLs", ctx, id)
	ret0, _ := ret[0].([]*entity.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserURLs indicates an expected call of FindUserURLs.
func (mr *MockUserDBMockRecorder) FindUserURLs(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserURLs", reflect.TypeOf((*MockUserDB)(nil).FindUserURLs), ctx, id)
}

// MarkURLAsDeleted mocks base method.
func (m *MockUserDB) MarkURLAsDeleted(ctx context.Context, userID int, aliases []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkURLAsDeleted", ctx, userID, aliases)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkURLAsDeleted indicates an expected call of MarkURLAsDeleted.
func (mr *MockUserDBMockRecorder) MarkURLAsDeleted(ctx, userID, aliases any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkURLAsDeleted", reflect.TypeOf((*MockUserDB)(nil).MarkURLAsDeleted), ctx, userID, aliases)
}

// SaveUser mocks base method.
func (m *MockUserDB) SaveUser(ctx context.Context) (*entity0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx)
	ret0, _ := ret[0].(*entity0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserDBMockRecorder) SaveUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserDB)(nil).SaveUser), ctx)
}
