// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: internal/grpc/stats/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_internal_grpc_stats_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_stats_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_stats_stats_proto_rawDescGZIP(), []int{0}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlsCount     int64                  `protobuf:"varint,1,opt,name=urls_count,json=urlsCount,proto3" json:"urls_count,omitempty"`
	UsersCount    int64                  `protobuf:"varint,2,opt,name=users_count,json=usersCount,proto3" json:"users_count,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_internal_grpc_stats_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_stats_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetUrlsCount() int64 {
	if x != nil {
		return x.UrlsCount
	}
	return 0
}

func (x *GetStatsResponse) GetUsersCount() int64 {
	if x != nil {
		return x.UsersCount
	}
	return 0
}

func (x *GetStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_grpc_stats_stats_proto protoreflect.FileDescriptor

const file_internal_grpc_stats_stats_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/grpc/stats/stats.proto\x12\x05stats\"\x11\n" +
	"\x0fGetStatsRequest\"h\n" +
	"\x10GetStatsResponse\x12\x1d\n" +
	"\n" +
	"urls_count\x18\x01 \x01(\x03R\turlsCount\x12\x1f\n" +
	"\vusers_count\x18\x02 \x01(\x03R\n" +
	"usersCount\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2K\n" +
	"\fStatsService\x12;\n" +
	"\bGetStats\x12\x16.stats.GetStatsRequest\x1a\x17.stats.GetStatsResponseB3Z1github.com/gururuby/shortener/internal/grpc/statsb\x06proto3"

var (
	file_internal_grpc_stats_stats_proto_rawDescOnce sync.Once
	file_internal_grpc_stats_stats_proto_rawDescData []byte
)

func file_internal_grpc_stats_stats_proto_rawDescGZIP() []byte {
	file_internal_grpc_stats_stats_proto_rawDescOnce.Do(func() {
		file_internal_grpc_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_stats_stats_proto_rawDesc), len(file_internal_grpc_stats_stats_proto_rawDesc)))
	})
	return file_internal_grpc_stats_stats_proto_rawDescData
}

var file_internal_grpc_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_stats_stats_proto_goTypes = []any{
	(*GetStatsRequest)(nil),  // 0: stats.GetStatsRequest
	(*GetStatsResponse)(nil), // 1: stats.GetStatsResponse
}
var file_internal_grpc_stats_stats_proto_depIdxs = []int32{
	0, // 0: stats.StatsService.GetStats:input_type -> stats.GetStatsRequest
	1, // 1: stats.StatsService.GetStats:output_type -> stats.GetStatsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_stats_stats_proto_init() }
func file_internal_grpc_stats_stats_proto_init() {
	if File_internal_grpc_stats_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_stats_stats_proto_rawDesc), len(file_internal_grpc_stats_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_stats_stats_proto_goTypes,
		DependencyIndexes: file_internal_grpc_stats_stats_proto_depIdxs,
		MessageInfos:      file_internal_grpc_stats_stats_proto_msgTypes,
	}.Build()
	File_internal_grpc_stats_stats_proto = out.File
	file_internal_grpc_stats_stats_proto_goTypes = nil
	file_internal_grpc_stats_stats_proto_depIdxs = nil
}
